import type { GraphNode, GraphEdge } from '@ai-security-architect/graph';
import type { AttackPath } from '@ai-security-architect/core';

export const GOLDEN_FIXTURE_NODES: GraphNode[] = [
  {
    asset: {
      id: 'asset-internet',
      tenantId: 'tenant-enterprise-01',
      type: 'INTERNET',
      name: 'Public Internet (0.0.0.0/0)',
      environment: 'external',
      isPublic: true,
      isSensitiveData: false,
      criticality: 'LOW',
      metadata: {},
      tags: ['public', 'entry-point'],
    },
    findings: [],
    inDegree: 0,
    outDegree: 1,
  },
  {
    asset: {
      id: 'asset-alb-production-public-alb',
      tenantId: 'tenant-enterprise-01',
      type: 'LOAD_BALANCER',
      name: 'production-public-alb',
      environment: 'production',
      isPublic: true,
      isSensitiveData: false,
      criticality: 'HIGH',
      metadata: { filePath: 'terraform/alb.tf', protocol: 'HTTP', port: 80 },
      tags: ['aws', 'load-balancer', 'public-ingress'],
    },
    findings: [
      {
        id: 'finding-iac-alb-http-15',
        tenantId: 'tenant-enterprise-01',
        assetId: 'asset-alb-production-public-alb',
        category: 'PUBLIC_EXPOSURE',
        ruleId: 'ALB-INSECURE-HTTP-LISTENER',
        title: 'Application Load Balancer Insecure HTTP Listener (Port 80)',
        description: 'The load balancer listener accepts unencrypted plaintext HTTP traffic on port 80 without automatic TLS redirection.',
        severity: 'MEDIUM',
        confidence: 'HIGH',
        scanner: 'IacTerraformAnalyzer',
        evidence: {
          id: 'ev-iac-alb-http-15',
          tenantId: 'tenant-enterprise-01',
          sourceType: 'TERRAFORM',
          repository: 'enterprise/multi-tier-app',
          filePath: 'terraform/alb.tf',
          lineStart: 15,
          lineEnd: 24,
          snippet: 'resource "aws_lb_listener" "http" {\n  load_balancer_arn = aws_lb.public_alb.arn\n  port = 80\n  protocol = "HTTP"\n}',
          snippetSha256: '9f83cf4b1b369c3a078bf010777fa6574f17737c357ec394b0d87fa541d1a8e2',
          scanner: 'IacTerraformAnalyzer',
          timestamp: '2026-08-24T12:00:00.000Z',
        },
        metadata: {},
      },
    ],
    inDegree: 1,
    outDegree: 1,
  },
  {
    asset: {
      id: 'asset-svc-order',
      tenantId: 'tenant-enterprise-01',
      type: 'SERVICE',
      name: 'order-service',
      environment: 'production',
      isPublic: false,
      isSensitiveData: false,
      criticality: 'HIGH',
      metadata: { framework: 'spring-boot', language: 'java' },
      tags: ['backend', 'spring-boot'],
    },
    findings: [],
    inDegree: 1,
    outDegree: 2,
  },
  {
    asset: {
      id: 'asset-endpoint-order-post-_api_v1_orders_webhook_callback',
      tenantId: 'tenant-enterprise-01',
      type: 'ENDPOINT',
      name: '/api/v1/orders/webhook-callback',
      environment: 'production',
      isPublic: false,
      isSensitiveData: false,
      criticality: 'HIGH',
      metadata: {
        httpMethod: 'POST',
        filePath: 'OrderController.java',
        lineStart: 25,
      },
      tags: ['endpoint', 'POST'],
    },
    findings: [
      {
        id: 'finding-ssrf-OrderController_java-25',
        tenantId: 'tenant-enterprise-01',
        assetId: 'asset-endpoint-order-post-_api_v1_orders_webhook_callback',
        category: 'SSRF',
        ruleId: 'SSRF-SPRING-URL-CONNECTION',
        title: 'Server-Side Request Forgery via Unvalidated Webhook URL',
        description: 'The application receives a user-controllable URL and establishes an outbound HTTP connection without IP or domain allowlist validation. In cloud environments, this enables attackers to access the AWS Instance Metadata Service (IMDS at 169.254.169.254) and retrieve temporary IAM credentials.',
        severity: 'HIGH',
        confidence: 'HIGH',
        scanner: 'SastCodeAnalyzer',
        cwe: 'CWE-918',
        evidence: {
          id: 'ev-sast-ssrf-OrderController_java-25',
          tenantId: 'tenant-enterprise-01',
          sourceType: 'SOURCE_CODE',
          repository: 'enterprise/multi-tier-app',
          filePath: 'src/main/java/com/enterprise/order/OrderController.java',
          lineStart: 25,
          lineEnd: 35,
          snippet: 'URL url = new URL(callbackUrl);\nHttpURLConnection conn = (HttpURLConnection) url.openConnection();\nconn.setRequestMethod("GET");',
          snippetSha256: '4a1b18cf32d2179ec039fbe54d7328bfef125740445d4e1017b2bcf1b37ad5e9',
          scanner: 'SastCodeAnalyzer',
          timestamp: '2026-08-24T12:00:00.000Z',
        },
        metadata: {},
      },
    ],
    inDegree: 1,
    outDegree: 1,
  },
  {
    asset: {
      id: 'asset-k8s-pod-order-service',
      tenantId: 'tenant-enterprise-01',
      type: 'POD',
      name: 'order-service-pod',
      environment: 'production',
      isPublic: false,
      isSensitiveData: false,
      criticality: 'MEDIUM',
      metadata: { namespace: 'production', serviceAccountName: 'order-service-sa' },
      tags: ['kubernetes', 'pod'],
    },
    findings: [],
    inDegree: 1,
    outDegree: 1,
  },
  {
    asset: {
      id: 'asset-k8s-sa-order-service-sa',
      tenantId: 'tenant-enterprise-01',
      type: 'KUBERNETES_SERVICE_ACCOUNT',
      name: 'order-service-sa',
      environment: 'production',
      isPublic: false,
      isSensitiveData: false,
      criticality: 'HIGH',
      metadata: {
        namespace: 'production',
        awsRoleArn: 'arn:aws:iam::123456789012:role/order-service-role',
      },
      tags: ['kubernetes', 'service-account'],
    },
    findings: [],
    inDegree: 1,
    outDegree: 1,
  },
  {
    asset: {
      id: 'asset-iam-role-order-service-role',
      tenantId: 'tenant-enterprise-01',
      type: 'IAM_ROLE',
      name: 'order-service-role',
      environment: 'cloud',
      isPublic: false,
      isSensitiveData: false,
      criticality: 'CRITICAL',
      metadata: {
        arn: 'arn:aws:iam::123456789012:role/order-service-role',
      },
      tags: ['aws', 'iam', 'wildcard-policy'],
    },
    findings: [
      {
        id: 'finding-iac-iam-wildcard-s3-order_service_s3_wildcard',
        tenantId: 'tenant-enterprise-01',
        assetId: 'asset-iam-role-order-service-role',
        category: 'IAM_OVERPRIVILEGE',
        ruleId: 'IAM-WILDCARD-S3-PERMISSION',
        title: 'Wildcard Action s3:* on IAM Role Policy',
        description: 'The IAM policy grants unrestricted wildcard permissions ("s3:*") on resources. Any workload assuming this role gains complete administrative control, data exfiltration, and deletion capabilities across all S3 buckets in the AWS account.',
        severity: 'CRITICAL',
        confidence: 'CERTAIN',
        scanner: 'IacTerraformAnalyzer',
        evidence: {
          id: 'ev-iac-wildcard-s3-terraform_iam_tf-18',
          tenantId: 'tenant-enterprise-01',
          sourceType: 'TERRAFORM',
          repository: 'enterprise/multi-tier-app',
          filePath: 'terraform/iam.tf',
          lineStart: 18,
          lineEnd: 32,
          snippet: 'resource "aws_iam_role_policy" "order_service_s3_wildcard" {\n  name = "order-service-s3-wildcard"\n  role = aws_iam_role.order_service_role.id\n  policy = jsonencode({\n    Version = "2012-10-17"\n    Statement = [{\n      Effect = "Allow"\n      Action = "s3:*"\n      Resource = "*"\n    }]\n  })\n}',
          snippetSha256: '9211c47dbf3b927ac0219ffef29487b3fa92b3a887b47df2c01991d8487fa281',
          scanner: 'IacTerraformAnalyzer',
          timestamp: '2026-08-24T12:00:00.000Z',
        },
        metadata: {},
      },
    ],
    inDegree: 1,
    outDegree: 1,
  },
  {
    asset: {
      id: 'asset-s3-enterprise-production-customer-pii',
      tenantId: 'tenant-enterprise-01',
      type: 'BUCKET',
      name: 'enterprise-production-customer-pii',
      environment: 'production',
      isPublic: false,
      isSensitiveData: true,
      criticality: 'CRITICAL',
      metadata: { containsPII: true, dataClassification: 'CONFIDENTIAL_PII' },
      tags: ['aws', 's3', 'sensitive-data', 'crown-jewel'],
    },
    findings: [],
    inDegree: 1,
    outDegree: 0,
  },
];

export const GOLDEN_FIXTURE_EDGES: GraphEdge[] = [
  {
    relationship: {
      id: 'rel-internet-alb',
      tenantId: 'tenant-enterprise-01',
      sourceAssetId: 'asset-internet',
      targetAssetId: 'asset-alb-production-public-alb',
      type: 'EXPOSES_HTTP',
      nature: 'DECLARED',
      confidence: 1.0,
      metadata: {},
    },
    sourceAssetId: 'asset-internet',
    targetAssetId: 'asset-alb-production-public-alb',
    type: 'EXPOSES_HTTP',
    confidence: 1.0,
  },
  {
    relationship: {
      id: 'rel-alb-svc',
      tenantId: 'tenant-enterprise-01',
      sourceAssetId: 'asset-alb-production-public-alb',
      targetAssetId: 'asset-svc-order',
      type: 'ROUTES_TO',
      nature: 'INFERRED',
      confidence: 0.95,
      metadata: {},
    },
    sourceAssetId: 'asset-alb-production-public-alb',
    targetAssetId: 'asset-svc-order',
    type: 'ROUTES_TO',
    confidence: 0.95,
  },
  {
    relationship: {
      id: 'rel-svc-endpoint',
      tenantId: 'tenant-enterprise-01',
      sourceAssetId: 'asset-svc-order',
      targetAssetId: 'asset-endpoint-order-post-_api_v1_orders_webhook_callback',
      type: 'CONTAINS',
      nature: 'DECLARED',
      confidence: 1.0,
      metadata: {},
    },
    sourceAssetId: 'asset-svc-order',
    targetAssetId: 'asset-endpoint-order-post-_api_v1_orders_webhook_callback',
    type: 'CONTAINS',
    confidence: 1.0,
  },
  {
    relationship: {
      id: 'rel-svc-pod',
      tenantId: 'tenant-enterprise-01',
      sourceAssetId: 'asset-svc-order',
      targetAssetId: 'asset-k8s-pod-order-service',
      type: 'DEPLOYED_TO',
      nature: 'INFERRED',
      confidence: 0.95,
      metadata: {},
    },
    sourceAssetId: 'asset-svc-order',
    targetAssetId: 'asset-k8s-pod-order-service',
    type: 'DEPLOYED_TO',
    confidence: 0.95,
  },
  {
    relationship: {
      id: 'rel-pod-sa',
      tenantId: 'tenant-enterprise-01',
      sourceAssetId: 'asset-k8s-pod-order-service',
      targetAssetId: 'asset-k8s-sa-order-service-sa',
      type: 'RUNS_AS',
      nature: 'DECLARED',
      confidence: 1.0,
      metadata: {},
    },
    sourceAssetId: 'asset-k8s-pod-order-service',
    targetAssetId: 'asset-k8s-sa-order-service-sa',
    type: 'RUNS_AS',
    confidence: 1.0,
  },
  {
    relationship: {
      id: 'rel-sa-iam',
      tenantId: 'tenant-enterprise-01',
      sourceAssetId: 'asset-k8s-sa-order-service-sa',
      targetAssetId: 'asset-iam-role-order-service-role',
      type: 'ASSUMES_ROLE',
      nature: 'DECLARED',
      confidence: 1.0,
      metadata: {},
    },
    sourceAssetId: 'asset-k8s-sa-order-service-sa',
    targetAssetId: 'asset-iam-role-order-service-role',
    type: 'ASSUMES_ROLE',
    confidence: 1.0,
  },
  {
    relationship: {
      id: 'rel-iam-s3-chokepoint',
      tenantId: 'tenant-enterprise-01',
      sourceAssetId: 'asset-iam-role-order-service-role',
      targetAssetId: 'asset-s3-enterprise-production-customer-pii',
      type: 'CAN_READ',
      nature: 'INFERRED',
      confidence: 0.95,
      metadata: {},
    },
    sourceAssetId: 'asset-iam-role-order-service-role',
    targetAssetId: 'asset-s3-enterprise-production-customer-pii',
    type: 'CAN_READ',
    confidence: 0.95,
  },
];

export const GOLDEN_FIXTURE_ATTACK_PATH: AttackPath = {
  id: 'path-001',
  tenantId: 'tenant-enterprise-01',
  entryAssetId: 'asset-internet',
  targetAssetId: 'asset-s3-enterprise-production-customer-pii',
  pathLength: 6,
  steps: [
    {
      stepNumber: 1,
      sourceAssetId: 'asset-internet',
      targetAssetId: 'asset-alb-production-public-alb',
      relationshipType: 'EXPOSES_HTTP',
      explanation: 'Public internet traffic accesses exposed ingress endpoint on Application Load Balancer',
    },
    {
      stepNumber: 2,
      sourceAssetId: 'asset-alb-production-public-alb',
      targetAssetId: 'asset-svc-order',
      relationshipType: 'ROUTES_TO',
      explanation: 'Ingress load balancer forwards HTTP requests to order-service',
    },
    {
      stepNumber: 3,
      sourceAssetId: 'asset-svc-order',
      targetAssetId: 'asset-k8s-pod-order-service',
      relationshipType: 'DEPLOYED_TO',
      explanation: 'Order service executes inside Kubernetes Pod order-service-pod',
    },
    {
      stepNumber: 4,
      sourceAssetId: 'asset-k8s-pod-order-service',
      targetAssetId: 'asset-k8s-sa-order-service-sa',
      relationshipType: 'RUNS_AS',
      explanation: 'Pod runs under the identity of Kubernetes ServiceAccount order-service-sa',
    },
    {
      stepNumber: 5,
      sourceAssetId: 'asset-k8s-sa-order-service-sa',
      targetAssetId: 'asset-iam-role-order-service-role',
      relationshipType: 'ASSUMES_ROLE',
      findingId: 'finding-ssrf-OrderController_java-25',
      explanation: 'SSRF vulnerability allows workload to query AWS IMDS (169.254.169.254) and assume AWS IAM Role order-service-role',
    },
    {
      stepNumber: 6,
      sourceAssetId: 'asset-iam-role-order-service-role',
      targetAssetId: 'asset-s3-enterprise-production-customer-pii',
      relationshipType: 'CAN_READ',
      findingId: 'finding-iac-iam-wildcard-s3-order_service_s3_wildcard',
      explanation: 'Assumed IAM role grants s3:* wildcard permissions to sensitive S3 bucket containing confidential customer PII',
    },
  ],
  riskScore: {
    impact: 9.5,
    exploitability: 9.0,
    reachability: 1.0,
    assetCriticality: 10.0,
    confidence: 0.96,
    totalRisk: 9.2,
  },
  recommendedChokePoint: {
    edgeId: 'rel-iam-s3-chokepoint',
    sourceAssetId: 'asset-iam-role-order-service-role',
    targetAssetId: 'asset-s3-enterprise-production-customer-pii',
    relationshipType: 'CAN_READ',
    actionDescription: 'Scope IAM policy on order-service-role from wildcard s3:* to specific needed buckets or read-only access with condition keys',
    pathsEliminatedCount: 1,
    riskReductionPercentage: 100,
    engineeringEffort: 'LOW',
    blastRadius: 'LOW',
  },
  verifiedEliminated: false,
};
