import type { AttackPath, AIReasoningOutput } from '@ai-security-architect/core';
import type { VerificationResult, CandidatePatch } from './types.js';

export interface PrBotOptions {
  authorName?: string;
  authorEmail?: string;
  baseBranch?: string;
  labels?: string[];
  signOff?: boolean;
}

export interface PrPackage {
  title: string;
  headBranch: string;
  baseBranch: string;
  commitMessage: string;
  bodyMarkdown: string;
  unifiedDiff: string;
  modifiedFiles: string[];
  labels: string[];
  minCutProof: {
    chokePointTarget: string;
    severedEdges: string[];
    riskBefore: number;
    riskAfter: number;
    riskReductionPercentage: number;
  };
}

export class AutonomousPrBot {
  private readonly authorName: string;
  private readonly authorEmail: string;
  private readonly baseBranch: string;
  private readonly defaultLabels: string[];
  private readonly signOff: boolean;

  constructor(options: PrBotOptions = {}) {
    this.authorName = options.authorName ?? 'AI Security Architect';
    this.authorEmail = options.authorEmail ?? 'bot@ai-security-architect.local';
    this.baseBranch = options.baseBranch ?? 'main';
    this.defaultLabels = options.labels ?? ['security', 'automated-remediation', 'attack-path-severed'];
    this.signOff = options.signOff ?? true;
  }

  public buildPrPackage(input: {
    attackPath: AttackPath;
    reasoningOutput: AIReasoningOutput;
    verification: VerificationResult;
    candidatePatches: CandidatePatch[];
  }): PrPackage {
    const { attackPath, reasoningOutput, verification, candidatePatches } = input;

    const shortTarget = attackPath.targetAssetId
      .replace(/^(asset|s3|db|role)-/i, '')
      .substring(0, 24);

    const title = `fix(security): sever attack path ${attackPath.id} to ${shortTarget} (-${verification.riskReductionPercentage}%)`;
    const headBranch = `security/remediate-${attackPath.id}-${shortTarget.toLowerCase().replace(/[^a-z0-9_-]/g, '-')}`;

    // Combine diffs
    const unifiedDiff = candidatePatches
      .map((p) => p.diff.trim())
      .filter(Boolean)
      .join('\n\n');

    const modifiedFiles = Array.from(new Set(candidatePatches.map((p) => p.filePath)));

    // Generate Commit Message
    let commitMessage = `${title}\n\nAutomated remediation by AI Security Architect.\n` +
      `- Severed attack path ${attackPath.id} (${attackPath.entryAssetId} -> ${attackPath.targetAssetId})\n` +
      `- Initial risk: ${verification.initialRiskScore.toFixed(1)}/10.0 -> Post-remediation risk: ${verification.postRemediationRiskScore.toFixed(1)}/10.0\n` +
      `- Risk reduction: -${verification.riskReductionPercentage}%\n` +
      `- Severed choke point edges: ${verification.severedEdges.join(', ') || 'N/A'}\n`;

    if (this.signOff) {
      commitMessage += `\nSigned-off-by: ${this.authorName} <${this.authorEmail}>\n`;
    }

    // Markdown PR Body with Min-Cut Proof and Metrics
    const bodyMarkdown = [
      `## 🛡️ AI Security Architect — Autonomous Remediation Pull Request`,
      ``,
      `### 📌 Summary`,
      reasoningOutput.summary,
      ``,
      `### 🔍 Exploit Chain & Root Cause`,
      reasoningOutput.rootCauseAnalysis,
      ``,
      `**Business Impact:** ${reasoningOutput.businessImpact}`,
      ``,
      `### 📐 Min-Cut Security Proof & Verification Delta`,
      `This change severs the critical graph choke point identified by the Dinic min-cut theorem. Closed-loop verification passed with 0 security regressions.`,
      ``,
      `| Metric | Before Patch | After Patch | Delta |`,
      `| :--- | :--- | :--- | :--- |`,
      `| **Path Risk Score** | **${verification.initialRiskScore.toFixed(1)} / 10.0** | **${verification.postRemediationRiskScore.toFixed(1)} / 10.0** | **-${verification.riskReductionPercentage}%** |`,
      `| **Active Exploit Paths** | **${verification.pathsEliminatedCount + verification.remainingPathsCount}** | **${verification.remainingPathsCount}** | **-${verification.pathsEliminatedCount}** |`,
      `| **Security Regressions** | **0** | **${verification.newRegressionsCount}** | **0 (CLEAN)** |`,
      `| **Verification Status** | Vulnerable | Verified Clean ✅ | **PASSED** |`,
      ``,
      `### ✂️ Severed Graph Edges`,
      verification.severedEdges.length > 0
        ? verification.severedEdges.map((e) => `- \`${e}\``).join('\n')
        : `- (Direct asset configuration remediation)`,
      ``,
      `### 📁 Modified Files (${modifiedFiles.length})`,
      modifiedFiles.map((f) => `- \`${f}\``).join('\n'),
      ``,
      `### 🔒 Evidence References`,
      reasoningOutput.evidenceReferences.map((e) => `- Evidence Citation: \`${e}\``).join('\n'),
      ``,
      `---`,
      `> *Autonomous PR generated by @ai-security-architect/remediation at ${verification.verificationTimestamp}*`,
    ].join('\n');

    return {
      title,
      headBranch,
      baseBranch: this.baseBranch,
      commitMessage,
      bodyMarkdown,
      unifiedDiff,
      modifiedFiles,
      labels: [...this.defaultLabels],
      minCutProof: {
        chokePointTarget: attackPath.targetAssetId,
        severedEdges: verification.severedEdges,
        riskBefore: verification.initialRiskScore,
        riskAfter: verification.postRemediationRiskScore,
        riskReductionPercentage: verification.riskReductionPercentage,
      },
    };
  }

  public prepareGitCommands(pkg: PrPackage): string[] {
    return [
      `git checkout -b "${pkg.headBranch}" "${pkg.baseBranch}"`,
      `git apply << 'EOF'\n${pkg.unifiedDiff}\nEOF`,
      `git commit -m "${pkg.commitMessage.replace(/"/g, '\\"')}"`,
      `git push origin "${pkg.headBranch}"`,
    ];
  }
}
